# -*- coding: utf-8 -*-
"""Multi-modal rumor detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LIWISFhHNeAZlVNGoNmgx_qmBJz8hLVk
"""

# =========================================================
# CAPSTONE: Multimodal Rumor Detection (Weibo)
# One-Unit Code: Data → Models → Training → Metrics → Comparison
# =========================================================

# -------------------------------
# SECTION 0: Imports & Global Seed (safe determinism)
# -------------------------------
import os, re, json, random
from pathlib import Path as P
import numpy as np, pandas as pd

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler

from torchvision import transforms, models
from PIL import Image

from transformers import AutoTokenizer, AutoModel, set_seed as hf_set_seed

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    classification_report, confusion_matrix, accuracy_score, f1_score,
    roc_curve, auc, precision_recall_curve, average_precision_score
)

import matplotlib.pyplot as plt

SEED = 42
def set_global_seed(seed=42):
    os.environ["PYTHONHASHSEED"] = str(seed)
    os.environ["CUBLAS_WORKSPACE_CONFIG"] = ":4096:8"   # no crash with CUDA>=10.2
    os.environ["TORCH_ALLOW_TF32_CUDA"] = "0"
    os.environ["NVIDIA_TF32_OVERRIDE"] = "0"
    random.seed(seed); np.random.seed(seed); torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed); torch.cuda.manual_seed_all(seed)
    hf_set_seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    # don't force strict deterministic algorithms to avoid cuBLAS runtime error
    torch.use_deterministic_algorithms(False)

set_global_seed(SEED)

DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
TOKENIZER_NAME = 'bert-base-chinese'
tokenizer = AutoTokenizer.from_pretrained(TOKENIZER_NAME)

# -------------------------------
# SECTION 1: Paths & Data Loading
# -------------------------------
from google.colab import drive
drive.mount('/content/drive')

DATA_ROOT = "/content/drive/MyDrive/CAPSTONE PROJECT/weibo"
TWEETS_DIR = f"{DATA_ROOT}/tweets"
ROOT = P(DATA_ROOT)

# optional explicit val files are tolerated
FILES = {
    "train_rumor":     (1, "train"),
    "train_nonrumor":  (0, "train"),
    "val_rumor":       (1, "val"),    # ok if missing
    "val_nonrumor":    (0, "val"),    # ok if missing
    "test_rumor":      (1, "test"),
    "test_nonrumor":   (0, "test"),
}

def parse_labeled_file(path: P, label: int, split: str):
    rows=[]
    with open(path, "r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            line=line.strip()
            if not line: continue
            if line.startswith("{") and line.endswith("}"):
                try:
                    j = json.loads(line); pid=None; txt=""
                    for k in ["post_id","id","weibo_id","mid"]:
                        if k in j: pid=str(j[k]); break
                    for k in ["text","content","weibo_text","tweet"]:
                        if k in j: txt=str(j[k]); break
                    if pid and txt:
                        m=re.search(r"(\d{6,})", pid)
                        if m: rows.append({"post_id": m.group(1), "text": txt, "label": label, "split": split}); continue
                except Exception: pass
            matched=False
            for sep in ["\t","|||","|",",",":",";"]:
                if sep in line:
                    a,b = [x.strip() for x in line.split(sep,1)]
                    m=re.search(r"(\d{6,})", a)
                    if m: rows.append({"post_id": m.group(1), "text": b, "label": label, "split": split}); matched=True; break
            if matched: continue
            m=re.search(r"(\d{6,})", line)
            if m:
                pid=m.group(1); txt=line.replace(pid,"").strip(" |,:;\t-")
                rows.append({"post_id": pid, "text": txt, "label": label, "split": split})
    df = pd.DataFrame(rows).dropna().reset_index(drop=True)
    if not df.empty:
        df["len"]=df["text"].astype(str).str.len()
        df=df.sort_values("len", ascending=False).drop_duplicates("post_id").drop(columns=["len"])
    return df

TWEETS_DIR_P = P(TWEETS_DIR); assert TWEETS_DIR_P.exists(), f"tweets folder not found: {TWEETS_DIR_P}"
parts=[]
for fname, (lab, split) in FILES.items():
    p = TWEETS_DIR_P/fname
    if not p.exists():
        for ext in ["", ".txt", ".csv"]:
            q = TWEETS_DIR_P/(fname+ext)
            if q.exists(): p=q; break
    if not p.exists(): continue
    parts.append(parse_labeled_file(p, lab, split))
assert len(parts)>0, "No input tweet files found."
df_txt = pd.concat(parts, axis=0).reset_index(drop=True)

# -------------------------------
# SECTION 2: Image Collection & Merge
# -------------------------------
def extract_id_from_filename(p: P):
    m = re.match(r"^(\d{6,})", p.stem)
    return m.group(1) if m else None

def collect_images(root: P):
    exts = {".jpg",".jpeg",".png",".bmp",".gif",".JPG",".JPEG",".PNG",".BMP"}
    rows=[]
    for label, sub in [(1,"rumor_images"), (0,"nonrumor_images")]:
        d = root/sub
        if not d.exists(): continue
        for p in d.iterdir():
            if p.is_file() and p.suffix in exts:
                pid = extract_id_from_filename(p)
                if pid: rows.append({"post_id": pid, "image_path": str(p), "label_img": label})
    return pd.DataFrame(rows)

df_img = collect_images(ROOT).drop_duplicates("post_id").reset_index(drop=True)
df = df_txt.merge(df_img, on="post_id", how="inner")
if "label_img" in df.columns:
    mism = (df["label"] != df["label_img"]).sum()
    if mism>0: print(f"⚠️ {mism} label mismatches between text files and folder names; proceeding with text labels.")
    df = df.drop(columns=["label_img"], errors="ignore")

def _exists(p):
    try: return P(p).exists()
    except: return False
df = df[df["image_path"].astype(str).str.strip()!=""].copy()
df = df[df["image_path"].apply(_exists)].reset_index(drop=True)
df["image_path"]=df["image_path"].apply(lambda p: str(P(p).resolve()))
assert df["post_id"].notna().all() and df["text"].notna().all()

# -------------------------------
# SECTION 3: Train/Val/Test Split (uses provided val if present)
# -------------------------------
splits_found = set(df["split"].unique())
assert {"train","test"} <= splits_found, f"Expected at least 'train' and 'test' in split column, got {splits_found}"
if "val" in splits_found:
    train_df = df[df["split"]=="train"].reset_index(drop=True)
    val_df   = df[df["split"]=="val"].reset_index(drop=True)
    test_df  = df[df["split"]=="test"].reset_index(drop=True)
else:
    train_all = df[df["split"]=="train"].reset_index(drop=True)
    test_df   = df[df["split"]=="test"].reset_index(drop=True)
    train_df, val_df = train_test_split(train_all, test_size=0.2, random_state=SEED, stratify=train_all["label"])
print(f"Train: {train_df.shape}, Val: {val_df.shape}, Test: {test_df.shape}")

# -------------------------------
# SECTION 4: Transforms, Datasets & Loaders (with optional oversampling)
# -------------------------------
IMG_TFMS = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485,0.456,0.406], std=[0.229,0.224,0.225]),
])

def try_open_rgb(path):
    p = P(path)
    try:
        with Image.open(p) as im: return im.convert("RGB")
    except Exception:
        return None

class TextOnlyDS(Dataset):
    def __init__(self, frame, tokenizer, max_len=128):
        self.df=frame.reset_index(drop=True); self.tok=tokenizer; self.max_len=max_len
    def __len__(self): return len(self.df)
    def __getitem__(self,i):
        r=self.df.iloc[i]
        enc=self.tok(str(r["text"]), padding='max_length', truncation=True, max_length=self.max_len, return_tensors='pt')
        enc={k:v.squeeze(0) for k,v in enc.items()}
        return enc, int(r["label"])

class ImageOnlyDS(Dataset):
    def __init__(self, frame): self.df=frame.reset_index(drop=True)
    def __len__(self): return len(self.df)
    def __getitem__(self,i):
        r=self.df.iloc[i]; img=try_open_rgb(r["image_path"])
        if img is None: raise FileNotFoundError(r["image_path"])
        return IMG_TFMS(img), int(r["label"])

class MultiModalDS(Dataset):
    def __init__(self, frame, tokenizer, max_len=128):
        self.df=frame.reset_index(drop=True); self.tok=tokenizer; self.max_len=max_len
    def __len__(self): return len(self.df)
    def __getitem__(self,i):
        r=self.df.iloc[i]
        enc=self.tok(str(r["text"]), padding='max_length', truncation=True, max_length=self.max_len, return_tensors='pt')
        enc={k:v.squeeze(0) for k,v in enc.items()}
        img=try_open_rgb(r["image_path"])
        if img is None: raise FileNotFoundError(r["image_path"])
        return enc, IMG_TFMS(img), int(r["label"])

def _seeded_generator():
    g=torch.Generator(); g.manual_seed(SEED); return g

def _oversample_sampler(labels):
    # inverse-frequency sampling
    labels = np.asarray(labels, dtype=int)
    class_counts = np.bincount(labels + (labels.min()==1)) if labels.min()>0 else np.bincount(labels)
    class_counts = class_counts[class_counts>0]
    weights = 1.0 / class_counts
    sample_weights = [weights[y] for y in labels]
    return WeightedRandomSampler(sample_weights, num_samples=len(sample_weights), replacement=True)

def make_text_loaders(train_df, val_df, test_df, tokenizer, bs=16, max_len=128, num_workers=0, oversample=True):
    train_ds=TextOnlyDS(train_df, tokenizer, max_len); val_ds=TextOnlyDS(val_df, tokenizer, max_len); test_ds=TextOnlyDS(test_df, tokenizer, max_len)
    sampler = _oversample_sampler(train_df["label"].tolist()) if oversample else None
    train_dl=DataLoader(train_ds, batch_size=bs, shuffle=(sampler is None), sampler=sampler,
                        num_workers=num_workers, generator=_seeded_generator())
    val_dl  =DataLoader(val_ds,   batch_size=bs, shuffle=False, num_workers=num_workers, generator=_seeded_generator())
    test_dl =DataLoader(test_ds,  batch_size=bs, shuffle=False, num_workers=num_workers, generator=_seeded_generator())
    return train_dl, val_dl, test_dl

def make_image_loaders(train_df, val_df, test_df, bs=32, num_workers=0, oversample=True):
    train_ds=ImageOnlyDS(train_df); val_ds=ImageOnlyDS(val_df); test_ds=ImageOnlyDS(test_df)
    sampler = _oversample_sampler(train_df["label"].tolist()) if oversample else None
    train_dl=DataLoader(train_ds, batch_size=bs, shuffle=(sampler is None), sampler=sampler,
                        num_workers=num_workers, generator=_seeded_generator())
    val_dl  =DataLoader(val_ds,   batch_size=bs, shuffle=False, num_workers=num_workers, generator=_seeded_generator())
    test_dl =DataLoader(test_ds,  batch_size=bs, shuffle=False, num_workers=num_workers, generator=_seeded_generator())
    return train_dl, val_dl, test_dl

def make_mm_loaders(train_df, val_df, test_df, tokenizer, bs=8, max_len=128, num_workers=0, oversample=True):
    train_ds=MultiModalDS(train_df, tokenizer, max_len); val_ds=MultiModalDS(val_df, tokenizer, max_len); test_ds=MultiModalDS(test_df, tokenizer, max_len)
    sampler = _oversample_sampler(train_df["label"].tolist()) if oversample else None
    train_dl=DataLoader(train_ds, batch_size=bs, shuffle=(sampler is None), sampler=sampler,
                        num_workers=num_workers, generator=_seeded_generator())
    val_dl  =DataLoader(val_ds,   batch_size=bs, shuffle=False, num_workers=num_workers, generator=_seeded_generator())
    test_dl =DataLoader(test_ds,  batch_size=bs, shuffle=False, num_workers=num_workers, generator=_seeded_generator())
    return train_dl, val_dl, test_dl

# -------------------------------
# SECTION 5: Models
# -------------------------------
def mask_mean(last_hidden_state, attention_mask):
    mask = attention_mask.unsqueeze(-1)
    s = (last_hidden_state * mask).sum(1)
    d = mask.sum(1).clamp(min=1)
    return s / d

class TextOnlyBERT(nn.Module):
    def __init__(self, model_name='bert-base-chinese', dropout=0.2, use_cls=False):
        super().__init__()
        self.bert=AutoModel.from_pretrained(model_name)
        h=self.bert.config.hidden_size; self.use_cls=use_cls
        self.head=nn.Sequential(nn.Dropout(dropout), nn.Linear(h,2))
    def forward(self, tx):
        out=self.bert(**tx)
        t = out.pooler_output if (self.use_cls and hasattr(out,"pooler_output") and out.pooler_output is not None) \
            else mask_mean(out.last_hidden_state, tx["attention_mask"])
        return self.head(t)

class ImageOnlyResNet(nn.Module):
    def __init__(self, arch='resnet18', pretrained=True, dropout=0.3):
        super().__init__()
        if arch=='resnet18':
            self.backbone=models.resnet18(weights=models.ResNet18_Weights.DEFAULT if pretrained else None)
        elif arch=='resnet50':
            self.backbone=models.resnet50(weights=models.ResNet50_Weights.DEFAULT if pretrained else None)
        else: raise ValueError("arch must be resnet18 or resnet50")
        feat=self.backbone.fc.in_features
        self.backbone.fc=nn.Sequential(nn.Dropout(dropout), nn.Linear(feat,2))
    def forward(self,im): return self.backbone(im)

class LateFusionStrong(nn.Module):
    def __init__(self, model_name='bert-base-chinese', img_arch='resnet18', dropout=0.3):
        super().__init__()
        self.txt=AutoModel.from_pretrained(model_name); tdim=self.txt.config.hidden_size
        self.img = models.resnet18(weights=models.ResNet18_Weights.DEFAULT) if img_arch=='resnet18' else models.resnet50(weights=models.ResNet50_Weights.DEFAULT)
        idim=self.img.fc.in_features; self.img.fc=nn.Identity()
        self.head=nn.Sequential(nn.Linear(tdim+idim,256), nn.ReLU(), nn.Dropout(dropout), nn.Linear(256,2))
    def forward(self,tx,im):
        t_last=self.txt(**tx).last_hidden_state
        t=mask_mean(t_last, tx["attention_mask"]); i=self.img(im)
        return self.head(torch.cat([t,i],dim=1))

class EarlyFusion(nn.Module):
    def __init__(self, model_name='bert-base-chinese', img_arch='resnet18', n_layers=1, n_heads=8, dropout=0.1):
        super().__init__()
        self.txt=AutoModel.from_pretrained(model_name); H=self.txt.config.hidden_size
        img=models.resnet18(weights=models.ResNet18_Weights.DEFAULT) if img_arch=='resnet18' else models.resnet50(weights=models.ResNet50_Weights.DEFAULT)
        idim=img.fc.in_features; img.fc=nn.Identity(); self.img=img; self.img_proj=nn.Linear(idim,H)
        enc=nn.TransformerEncoderLayer(d_model=H, nhead=n_heads, dropout=dropout, batch_first=True)
        self.fuser=nn.TransformerEncoder(enc, num_layers=n_layers)
        self.head=nn.Sequential(nn.Dropout(dropout), nn.Linear(H,2))
    def forward(self,tx,im):
        t_out=self.txt(**tx).last_hidden_state
        iv=self.img_proj(self.img(im)).unsqueeze(1)
        x=torch.cat([iv,t_out],dim=1)
        pad=None
        if "attention_mask" in tx:
            B,L=tx["attention_mask"].shape
            pad=(1-tx["attention_mask"]).bool()
            pad=torch.cat([torch.zeros(B,1,dtype=torch.bool,device=pad.device), pad], dim=1)
        z=self.fuser(x, src_key_padding_mask=pad)
        return self.head(z[:,0,:])

class AttentionFusion(nn.Module):
    def __init__(self, model_name='bert-base-chinese', img_arch='resnet18', heads=8, dropout=0.1):
        super().__init__()
        self.txt=AutoModel.from_pretrained(model_name); H=self.txt.config.hidden_size
        img=models.resnet18(weights=models.ResNet18_Weights.DEFAULT) if img_arch=='resnet18' else models.resnet50(weights=models.ResNet50_Weights.DEFAULT)
        idim=img.fc.in_features; img.fc=nn.Identity(); self.img=img; self.img_proj=nn.Linear(idim,H)
        self.attn=nn.MultiheadAttention(embed_dim=H, num_heads=heads, batch_first=True, dropout=dropout)
        self.head=nn.Sequential(nn.Linear(2*H,256), nn.ReLU(), nn.Dropout(dropout), nn.Linear(256,2))
    def forward(self,tx,im):
        t_last=self.txt(**tx).last_hidden_state
        t_mask=tx.get("attention_mask", None)
        iv=self.img_proj(self.img(im)).unsqueeze(1)
        key_padding=(t_mask==0) if t_mask is not None else None
        attended,_=self.attn(query=iv, key=t_last, value=t_last, key_padding_mask=key_padding)
        t_pooled=mask_mean(t_last, tx["attention_mask"])
        return self.head(torch.cat([attended.squeeze(1), t_pooled], dim=1))

# -------------------------------
# SECTION 6: Training & Eval Utils
# -------------------------------
def step_on_batch(model, batch, lossf):
    if len(batch)==2:
        x,y=batch; y=y.to(DEVICE, dtype=torch.long)
        if isinstance(x, dict): x={k:v.to(DEVICE) for k,v in x.items()}; logits=model(x)
        else: x=x.to(DEVICE); logits=model(x)
    else:
        enc,im,y=batch
        enc={k:v.to(DEVICE) for k,v in enc.items()}; im=im.to(DEVICE); y=y.to(DEVICE, dtype=torch.long)
        logits=model(enc,im)
    loss=lossf(logits,y); preds=torch.argmax(logits,dim=1)
    return loss, preds.detach().cpu(), y.detach().cpu(), logits.detach().cpu()

def train_one_epoch(model, loader, opt, lossf):
    model.train(); tot=0.0
    for batch in loader:
        opt.zero_grad()
        loss,_,_,_=step_on_batch(model,batch,lossf)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        opt.step(); tot+=loss.item()
    return tot/max(1,len(loader))

@torch.no_grad()
def eval_collect(model, loader):
    model.eval(); ys, ps, pr = [], [], []
    for batch in loader:
        _, preds, y, logits = step_on_batch(model, batch, nn.CrossEntropyLoss())
        prob_pos = F.softmax(logits, dim=1)[:,1]
        ys.append(y); pr.append(preds); ps.append(prob_pos)
    y_true=torch.cat(ys).numpy(); y_pred=torch.cat(pr).numpy(); y_prob=torch.cat(ps).numpy()
    return y_true, y_pred, y_prob

def show_confusion_matrix(y_true,y_pred,normalize=False,labels=(0,1),title="Confusion Matrix"):
    cm = confusion_matrix(y_true,y_pred,labels=labels,normalize='true' if normalize else None)
    fig,ax=plt.subplots(figsize=(4.5,4)); im=ax.imshow(cm,interpolation='nearest',cmap='Blues'); ax.figure.colorbar(im,ax=ax)
    ax.set(xticks=np.arange(len(labels)), yticks=np.arange(len(labels)),
           xticklabels=[str(l) for l in labels], yticklabels=[str(l) for l in labels],
           ylabel='True label', xlabel='Predicted label', title=title)
    th=cm.max()/2.
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            txt=f"{cm[i,j]:.2f}" if normalize else f"{int(cm[i,j])}"
            ax.text(j,i,txt,ha="center",va="center",color="white" if cm[i,j]>th else "black")
    plt.tight_layout(); plt.show()

def show_roc_pr_curves(y_true, y_prob, title_prefix=""):
    if len(np.unique(y_true))<2:
        print("ROC/PR curves require both classes present in y_true; skipping."); return None
    fpr,tpr,_=roc_curve(y_true,y_prob); roc_auc=auc(fpr,tpr)
    prec,rec,_=precision_recall_curve(y_true,y_prob); ap=average_precision_score(y_true,y_prob)
    plt.figure(figsize=(5,4)); plt.plot(fpr,tpr,lw=2,label=f"AUC = {roc_auc:.3f}"); plt.plot([0,1],[0,1],'--'); plt.xlabel("FPR"); plt.ylabel("TPR"); plt.title(f"{title_prefix} ROC"); plt.legend(); plt.tight_layout(); plt.show()
    plt.figure(figsize=(5,4)); plt.plot(rec,prec,lw=2,label=f"AP = {ap:.3f}"); plt.xlabel("Recall"); plt.ylabel("Precision"); plt.title(f"{title_prefix} PR"); plt.legend(); plt.tight_layout(); plt.show()
    return {"auc":roc_auc,"ap":ap}

def evaluate_all(model, loader, name="Model"):
    y_true,y_pred,y_prob=eval_collect(model,loader)
    acc=accuracy_score(y_true,y_pred); f1m=f1_score(y_true,y_pred,average='macro'); f1w=f1_score(y_true,y_pred,average='weighted')
    print(f"\n=== {name} ==="); print(f"Accuracy: {acc:.4f} | F1-macro: {f1m:.4f} | F1-weighted: {f1w:.4f}\n")
    print("Classification report:"); print(classification_report(y_true,y_pred,digits=4, zero_division=0))
    show_confusion_matrix(y_true,y_pred,normalize=False,title=f"{name} – Confusion Matrix (Counts)")
    show_confusion_matrix(y_true,y_pred,normalize=True,title=f"{name} – Confusion Matrix (Normalized)")
    curves=show_roc_pr_curves(y_true,y_prob,title_prefix=name)
    if curves is not None: print(f"AUC: {curves['auc']:.4f} | Average Precision (AP): {curves['ap']:.4f}")
    return {"name":name, "acc":acc, "f1_macro":f1m, "f1_weighted":f1w,
            "auc":None if curves is None else curves["auc"],
            "ap": None if curves is None else curves["ap"],
            "y_true":y_true, "y_pred":y_pred, "y_prob":y_prob}

def results_to_df(results):
    rows=[]
    for r in results:
        rows.append({
            "Model": r["name"],
            "Accuracy": round(r["acc"],4),
            "F1 (macro)": round(r["f1_macro"],4),
            "F1 (weighted)": round(r["f1_weighted"],4),
            "AUC": None if r.get("auc") is None else round(r["auc"],4),
            "AP":  None if r.get("ap")  is None else round(r["ap"],4),
        })
    return pd.DataFrame(rows)

def make_weighted_ce(train_df):
    # class-weighted CE for imbalance
    _, counts = np.unique(train_df["label"].values, return_counts=True)
    total = counts.sum()
    weights = total / (len(counts) * counts)
    w = torch.tensor(weights, dtype=torch.float32, device=DEVICE)
    return nn.CrossEntropyLoss(weight=w)

def best_threshold_from_val(model, val_loader):
    # maximize macro-F1 on val by scanning thresholds
    y_true, _, y_prob = eval_collect(model, val_loader)
    best_t, best_f1 = 0.5, -1.0
    for t in np.linspace(0.05, 0.95, 19):
        y_hat = (y_prob >= t).astype(int)
        f1 = f1_score(y_true, y_hat, average='macro')
        if f1>best_f1: best_f1, best_t = f1, t
    print(f"Best threshold on val for macro-F1: t={best_t:.2f} (F1={best_f1:.4f})")
    return best_t

# -------------------------------
# SECTION 7: Build DataLoaders (oversample only on TRAIN)
# -------------------------------
text_train_dl, text_val_dl, text_test_dl = make_text_loaders(train_df, val_df, test_df, tokenizer, bs=16, max_len=128, oversample=True)
img_train_dl,  img_val_dl,  img_test_dl  = make_image_loaders(train_df, val_df, test_df, bs=32, oversample=True)
mm_train_dl,   mm_val_dl,   mm_test_dl   = make_mm_loaders(train_df, val_df, test_df, tokenizer, bs=8, max_len=128, oversample=True)

# -------------------------------
# SECTION 8: Train & Evaluate
# -------------------------------
lossf = make_weighted_ce(train_df)

# Text-only
set_global_seed(SEED)
txt_model = TextOnlyBERT(model_name=TOKENIZER_NAME, dropout=0.2, use_cls=False).to(DEVICE)
opt = torch.optim.AdamW(txt_model.parameters(), lr=2e-5)
for ep in range(3):
    tr=train_one_epoch(txt_model, text_train_dl, opt, lossf); print(f"[Text] Epoch {ep+1} Train Loss: {tr:.4f}")
    evaluate_all(txt_model, text_val_dl, "Text-only BERT (val)")
res_text_test = evaluate_all(txt_model, text_test_dl, "Text-only BERT (test)")

# Image-only
set_global_seed(SEED)
img_model = ImageOnlyResNet(arch='resnet18', pretrained=True, dropout=0.3).to(DEVICE)
opt = torch.optim.Adam(img_model.parameters(), lr=1e-4)
for ep in range(5):
    tr=train_one_epoch(img_model, img_train_dl, opt, lossf); print(f"[Image] Epoch {ep+1} Train Loss: {tr:.4f}")
    evaluate_all(img_model, img_val_dl, "Image-only ResNet18 (val)")
res_img_test = evaluate_all(img_model, img_test_dl, "Image-only ResNet18 (test)")

# Late Fusion (+ threshold tuning)
set_global_seed(SEED)
late_model = LateFusionStrong(model_name=TOKENIZER_NAME, img_arch='resnet18', dropout=0.3).to(DEVICE)
opt = torch.optim.AdamW(late_model.parameters(), lr=1e-4)
for ep in range(5):
    tr=train_one_epoch(late_model, mm_train_dl, opt, lossf); print(f"[LateFusion] Epoch {ep+1} Train Loss: {tr:.4f}")
    evaluate_all(late_model, mm_val_dl, "Late Fusion (val)")
thr_late = best_threshold_from_val(late_model, mm_val_dl)
res_late_test = evaluate_all(late_model, mm_test_dl, "Late Fusion (test)")
# Tuned macro-F1 (printed separately)
y_true_late, _, y_prob_late = eval_collect(late_model, mm_test_dl)
print("Late Fusion (test) Tuned Macro-F1:", f1_score(y_true_late, (y_prob_late>=thr_late).astype(int), average='macro'))

# Early Fusion
set_global_seed(SEED)
early_model = EarlyFusion(model_name=TOKENIZER_NAME, img_arch='resnet18', n_layers=1, n_heads=8, dropout=0.1).to(DEVICE)
opt = torch.optim.AdamW(early_model.parameters(), lr=1e-4)
for ep in range(5):
    tr=train_one_epoch(early_model, mm_train_dl, opt, lossf); print(f"[EarlyFusion] Epoch {ep+1} Train Loss: {tr:.4f}")
    evaluate_all(early_model, mm_val_dl, "Early Fusion (val)")
res_early_test = evaluate_all(early_model, mm_test_dl, "Early Fusion (test)")

# Attention Fusion
set_global_seed(SEED)
attn_model = AttentionFusion(model_name=TOKENIZER_NAME, img_arch='resnet18', heads=8, dropout=0.1).to(DEVICE)
opt = torch.optim.AdamW(attn_model.parameters(), lr=1e-4)
for ep in range(5):
    tr=train_one_epoch(attn_model, mm_train_dl, opt, lossf); print(f"[AttnFusion] Epoch {ep+1} Train Loss: {tr:.4f}")
    evaluate_all(attn_model, mm_val_dl, "Attention Fusion (val)")
res_attn_test = evaluate_all(attn_model, mm_test_dl, "Attention Fusion (test)")

# -------------------------------
# SECTION 9: Compare & Export Tables (final, corrected)
# -------------------------------
test_df_metrics = results_to_df([
    res_text_test,
    res_img_test,
    res_late_test,
    res_early_test,
    res_attn_test
])
print("\n=== TEST COMPARISON TABLE ===")
print(test_df_metrics)
test_df_metrics.to_csv("test_model_comparison.csv", index=False)

# -------------------------------
# SECTION 10: (Optional) Hyperparameter Experiment stub
# -------------------------------
def run_experiment(model_ctor, train_dl, val_dl, lr_list=(1e-4,5e-5), drop_list=(0.1,0.3), epochs=3, label="EXP"):
    best={"f1":-1,"cfg":None,"state":None}
    for lr in lr_list:
        for dr in drop_list:
            set_global_seed(SEED)
            model=model_ctor(dropout=dr).to(DEVICE)
            opt=torch.optim.AdamW(model.parameters(), lr=lr)
            lossf=make_weighted_ce(train_df)
            print(f"\n[{label}] lr={lr} dropout={dr}")
            for ep in range(epochs):
                tr=train_one_epoch(model, train_dl, opt, lossf)
                print(f"  Epoch {ep+1} Train Loss: {tr:.4f}")
                metrics=evaluate_all(model, val_dl, name=f"{label} (val)")
            if metrics["f1_macro"]>best["f1"]:
                best={"f1":metrics["f1_macro"], "cfg":(lr,dr),
                      "state":{k:v.detach().cpu() for k,v in model.state_dict().items()}}
    print(f"\nBest F1={best['f1']:.4f} with lr={best['cfg'][0]} drop={best['cfg'][1]}")
    return best
# (leave commented to save GPU)
# best_late = run_experiment(lambda dropout: LateFusionStrong(TOKENIZER_NAME,'resnet18',dropout), mm_train_dl, mm_val_dl)

best_late = run_experiment(
    model_ctor=lambda dropout: AttentionFusion(model_name=TOKENIZER_NAME, img_arch='resnet18', dropout=dropout),
   train_dl=mm_train_dl, val_dl=mm_val_dl,
    lr_list=(1e-4, 5e-5, 2e-5), drop_list=(0.1, 0.3, 0.5), epochs=3, label="AttentionFusion")

